version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=${MYSQL_USER:-root}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD:-password}
      - DATABASE_NAME=${MYSQL_DATABASE:-nest_enterprise_dev}
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret_key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nest_enterprise_dev}
      - MYSQL_USER=${MYSQL_USER:-nestuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
